name: dev-story
description: "Multi-agent story execution: SM creates story, Dev implements, Tea tests, Dev reviews - with subagent orchestration and Phase 1 optimizations"
author: "BMad"
version: "7.0.0-phase-1-optimizations"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/dev-story"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# This is an action workflow (no output template document)
template: false

# Variables (can be provided by caller)
variables:
  story_path: ""
  run_tests_command: "auto" # 'auto' = infer from repo, or override with explicit command
  strict: true # if true, halt on validation failures
  story_dir: "{config_source}:dev_story_location" # Directory containing story markdown files
  story_selection_limit: 10
  run_until_complete: true # Continue through all tasks without pausing except on HALT conditions
  force_yolo: true # Hint executor to activate #yolo: skip optional prompts and elicitation

  # Multi-agent orchestration settings
  use_subagents: true # Enable Claude Code subagent integration
  parallel_analysis: true # Run independent analyses in parallel where possible
  smart_context_generation: true # Generate contexts in parallel, JSON optional if XML succeeds (Level 1.5)
  context_caching: true # Cache epic-level context for reuse across stories in same epic (Phase 1 NEW)
  incremental_validation: true # Validate each task as completed, reduce final validation (Phase 1 NEW)
  parallel_test_execution: true # Run unit, integration, E2E tests concurrently (Level 3.1)
  parallel_test_writing: true # Write unit, integration, E2E tests concurrently (Level 3.2)
  progressive_test_execution: true # Execute tests as they're written, not after all written (Level 3.4)
  cross_phase_overlap: true # Overlap adjacent phases when dependencies allow (Level 2)

# Recommended inputs
recommended_inputs:
  - epic_file: "Path to epic file or PRD containing requirements"
  - tech_spec: "Path to technical specification (optional)"
  - architecture_docs: "Path to architecture documentation (optional)"

# Required tools
required_tools:
  - read_file
  - write_file
  - search_repo
  - run_tests
  - list_files
  - file_info
  - Task # For invoking Claude Code subagents

# Agent orchestration configuration
agents:
  sm:
    agent_id: "bmm-sm"
    agent_name: "Bob"
    agent_path: "{project-root}/bmad/bmm/agents/sm.md"
    phases: [1]
    responsibilities:
      - "Create user story markdown from epic/PRD"
      - "Generate story context (XML/JSON)"
      - "Set story Status to Approved"
      - "Handoff to Dev for implementation"
    subagents:
      phase_1:
        - type: "bmm-requirements-analyst"
          description: "Analyzes and refines story requirements"
          when: "during-story-creation"
          parallel_group: "analysis" # Runs in parallel with epic-optimizer
        - type: "bmm-epic-optimizer"
          description: "Ensures story aligns with epic scope"
          when: "during-story-creation"
          parallel_group: "analysis" # Runs in parallel with requirements-analyst
        - type: "bmm-document-reviewer"
          description: "Reviews story completeness before handoff"
          when: "before-handoff"
          parallel_group: null # Runs after analysis group

  dev:
    agent_id: "bmm-dev"
    agent_name: "Amelia"
    agent_path: "{project-root}/bmad/bmm/agents/dev.md"
    phases: [2, 3, 5]
    responsibilities:
      - "Load story and context (created by SM)"
      - "Plan and execute implementation"
      - "Update story file with progress"
      - "Review completed story for quality and completeness"
    subagents:
      phase_2:
        - type: "bmm-codebase-analyzer"
          description: "Analyzes codebase structure and existing patterns"
          when: "before-implementation"
      phase_3:
        - type: "bmm-pattern-detector"
          description: "Validates code follows architectural patterns"
          when: "after-implementation"
          parallel_group: "validation" # Runs in parallel with dependency-mapper
        - type: "bmm-dependency-mapper"
          description: "Maps dependencies and integration points"
          when: "after-implementation"
          parallel_group: "validation" # Runs in parallel with pattern-detector
      phase_5:
        - type: "bmm-document-reviewer"
          description: "Reviews story documentation completeness"
          when: "before-review"
          parallel_group: "review" # Runs in parallel with requirements-analyst
        - type: "bmm-requirements-analyst"
          description: "Validates all acceptance criteria met"
          when: "during-review"
          parallel_group: "review" # Runs in parallel with document-reviewer

  tea:
    agent_id: "bmm-tea"
    agent_name: "Murat"
    agent_path: "{project-root}/bmad/bmm/agents/tea.md"
    phases: [4]
    responsibilities:
      - "Design comprehensive test strategy"
      - "Implement tests (unit, integration, E2E)"
      - "Execute tests and validate coverage"
      - "Run regression suite and quality gates"
    subagents:
      phase_4:
        - type: "bmm-test-coverage-analyzer"
          description: "Analyzes test coverage and identifies gaps"
          when: "after-test-implementation"
          parallel_group: "quality" # Runs in parallel with tech-debt-auditor
        - type: "bmm-tech-debt-auditor"
          description: "Identifies test-related technical debt"
          when: "during-validation"
          parallel_group: "quality" # Runs in parallel with test-coverage-analyzer

# Workflow phases with agent assignments
phases:
  - phase: 1
    name: "Story Creation & Context Generation"
    agent: "sm"
    lead: "Bob"
    description: |
      Create user story markdown from epic/PRD/tech-spec
      Generate comprehensive story context (XML/JSON)
      Analyze requirements for clarity and completeness
      Ensure story aligns with epic scope
      Set story Status to "Approved"
      Handoff to Dev (Amelia) for implementation
    steps: ["1.1", "1.2", "1.3", "1.4"]
    overlap_config:
      can_overlap_with: "phase-2"
      overlap_trigger:
        step: "1.1"
        condition: "story_file_created"
        signal_to_phase: 2
        signal_to_step: "2.2"
        signal_data: ["story_path"]
      wait_for_complete: true  # Phase 2 must wait for Phase 1 to fully complete before final steps
    context_tracking:
      input_tokens: 0
      output_tokens: 0
      subagent_tokens: 0
      total_tokens: 0
      time_estimate: "25-30 min"
      time_with_parallel: "15-20 min"  # Level 1: Parallel subagents
      time_with_overlap: "14-18 min"  # Level 2: -1 min (overlap with Phase 2)
      time_with_smart_context: "12-16 min"  # Level 1.5: -2 min (smart context generation)
      time_with_caching: "9-13 min"  # Context caching: -3 min (2nd+ story in epic only, first story unchanged)
    subagents:
      during:
        - "bmm-requirements-analyst"
        - "bmm-epic-optimizer"
      post:
        - "bmm-document-reviewer"
    handoff_to: "phase-2"
    handoff_data:
      - story_path
      - story_context_path
      - acceptance_criteria
      - tasks_list
      - epic_context
      - approval_status

  - phase: 2
    name: "Story Loading & Implementation Planning"
    agent: "dev"
    lead: "Amelia"
    description: |
      Load story file (Status=Approved from Bob)
      Load story context (XML/JSON from Bob)
      Parse acceptance criteria, tasks, dev notes
      Analyze codebase for implementation context
      Plan implementation approach
    steps: ["2.1", "2.2", "2.3"]
    early_start_config:
      can_start_early: true
      trigger_from_phase: 1
      trigger_from_step: "1.1"
      early_steps: ["2.2"]  # Codebase analysis can start early
      requires_from_phase_1: ["story_path"]  # Needs story file, not context yet
      must_wait_for_complete: ["2.1", "2.3"]  # These steps need full Phase 1 completion
    context_tracking:
      input_tokens: 0
      output_tokens: 0
      subagent_tokens: 0
      total_tokens: 0
      time_estimate: "15-20 min"
      time_with_parallel: "15-20 min"  # No within-phase parallelization
      time_with_overlap: "7-10 min"  # Level 2: -8 min (codebase analysis runs during Phase 1 step 1.2)
    subagents:
      pre:
        - "bmm-codebase-analyzer"
    handoff_to: "phase-3"
    handoff_data:
      - story_content
      - story_context
      - acceptance_criteria
      - tasks_list
      - implementation_plan
      - codebase_analysis

  - phase: 3
    name: "Implementation Execution"
    agent: "dev"
    lead: "Amelia"
    description: |
      Implement all tasks and subtasks
      Follow architectural patterns
      Handle edge cases and error conditions
      Update story progress (tasks checkboxes, dev notes)
      Validate implementation against patterns
    steps: ["3.1", "3.2", "3.3", "3.4"]
    overlap_config:
      can_overlap_with: "phase-4"
      overlap_trigger:
        step: "3.1"
        condition: "progress >= 0.75"  # 75% of tasks complete
        signal_to_phase: 4
        signal_to_step: "4.1"
        signal_data: ["acceptance_criteria", "partial_implementation", "completed_files"]
      wait_for_complete: false  # Phase 4 can start test design while Phase 3 finishes
    context_tracking:
      input_tokens: 0
      output_tokens: 0
      subagent_tokens: 0
      total_tokens: 0
      time_estimate: "120-180 min"
      time_with_parallel: "105-165 min"  # Level 1: Parallel validation
      time_with_overlap: "95-155 min"  # Level 2: -10 min (Phase 4 starts early)
      time_with_incremental: "90-150 min"  # Incremental validation: -5 min (validate as we go)
    subagents:
      post:
        - "bmm-pattern-detector"
        - "bmm-dependency-mapper"
    handoff_to: "phase-4"
    handoff_data:
      - implemented_files
      - changes_summary
      - patterns_validated
      - dependencies_mapped
      - story_updates

  - phase: 4
    name: "Testing & Validation"
    agent: "tea"
    lead: "Murat"
    description: |
      Design test strategy (unit, integration, E2E)
      Implement comprehensive tests IN PARALLEL
      Execute all tests IN PARALLEL (new + regression)
      Analyze coverage and identify gaps
      Validate quality gates
      Run linting and static analysis
    steps: ["4.1", "4.2", "4.3", "4.4", "4.5"]
    early_start_config:
      can_start_early: true
      trigger_from_phase: 3
      trigger_from_step: "3.1"
      trigger_condition: "progress >= 0.75"
      early_steps: ["4.1"]  # Test strategy design can start early
      requires_from_phase_3: ["acceptance_criteria", "partial_implementation"]
      must_wait_for_complete: ["4.2", "4.3", "4.4", "4.5"]  # Must wait for full implementation
    overlap_config:
      can_overlap_with: "phase-5"
      overlap_trigger:
        step: "4.3"
        condition: "all_tests_passing"
        signal_to_phase: 5
        signal_to_step: "5.1"
        signal_data: ["test_results", "test_files"]
      wait_for_complete: false  # Phase 5 can start doc review while quality gates run
    parallel_test_tasks:
      - task_id: "unit-tests"
        description: "Write unit tests for business logic"
        agent: "task-agent-1"
        scope: "tests/unit/**/*.test.ts(x)"
        coverage_target: "85%"
        estimated_time: 30
      - task_id: "integration-tests"
        description: "Write integration tests for component interactions"
        agent: "task-agent-2"
        scope: "tests/integration/**/*.test.ts(x)"
        coverage_focus: "API calls, state management, component integration"
        estimated_time: 20
      - task_id: "e2e-tests"
        description: "Write E2E tests for critical user flows"
        agent: "task-agent-3"
        scope: "tests/e2e/**/*.spec.ts(x)"
        conditional: "Only if story includes UI changes"
        estimated_time: 10
    context_tracking:
      input_tokens: 0
      output_tokens: 0
      subagent_tokens: 0
      total_tokens: 0
      time_estimate: "90-120 min"
      time_with_parallel: "38-68 min"  # L1 + L3.1 + L3.2: 52 min saved
      time_with_overlap: "28-58 min"  # Level 2: -10 min (early start from Phase 3)
      time_with_progressive: "22-52 min"  # Level 3.4: -6 min (progressive test execution)
    subagents:
      post:
        - "bmm-test-coverage-analyzer"
        - "bmm-tech-debt-auditor"
    handoff_to: "phase-5"
    handoff_data:
      - test_strategy
      - test_files
      - test_results
      - coverage_report
      - gaps_identified
      - quality_gate_status
      - lint_results

  - phase: 5
    name: "Story Review & Completion"
    agent: "dev"
    lead: "Amelia"
    description: |
      Review story documentation completeness
      Validate all acceptance criteria met
      Verify all tasks checked
      Confirm File List complete
      Validate Change Log updated
      Run final regression suite
      Set Status to "Ready for Review"
    steps: ["5.1", "5.2", "5.3", "5.4"]
    early_start_config:
      can_start_early: true
      trigger_from_phase: 4
      trigger_from_step: "4.3"
      trigger_condition: "all_tests_passing"
      early_steps: ["5.1"]  # Doc review can start early
      requires_from_phase_4: ["test_results", "test_files"]
      must_wait_for_complete: ["5.2", "5.3", "5.4"]  # Must wait for quality gates
    context_tracking:
      input_tokens: 0
      output_tokens: 0
      subagent_tokens: 0
      total_tokens: 0
      time_estimate: "20-30 min"
      time_with_parallel: "15-25 min"  # Level 1: Parallel review
      time_with_overlap: "11-21 min"  # Level 2: -4 min (early start from Phase 4)
    subagents:
      pre:
        - "bmm-document-reviewer"
      during:
        - "bmm-requirements-analyst"
    handoff_data:
      - review_results
      - validation_status
      - final_story_status
      - completion_summary

tags:
  - development
  - story-execution
  - tests
  - validation
  - bmad-v6
  - multi-agent
  - orchestration

execution_hints:
  interactive: false # Minimize prompts; intended to run to completion
  autonomous: true # Proceed without user input unless blocked
  iterative: true # Process tasks iteratively
  orchestrated: true # Use multi-agent orchestration pattern
  handoff_protocol: "explicit" # Require explicit handoff between agents
